<?php

namespace ContainerYgY6cL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Onmb1XService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..Onmb1X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Onmb1X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'game' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
        ], [
            'game' => 'App\\Repository\\GameRepository',
        ]);
    }
}
