<?php

namespace ContainerYgY6cL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminController' shared autowired service.
     *
     * @return \App\Controller\AdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminController'] = $instance = new \App\Controller\AdminController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\WinnersRepository'] ?? $container->load('getWinnersRepositoryService')), ($container->privates['App\\Repository\\DistributedTicketsRepository'] ?? $container->load('getDistributedTicketsRepositoryService')), ($container->privates['App\\Repository\\TicketsRepository'] ?? $container->load('getTicketsRepositoryService')), ($container->privates['App\\Repository\\GameRepository'] ?? $container->load('getGameRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\AdminController', $container));

        return $instance;
    }
}
