<?php

namespace ContainerYgY6cL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::deleteparticipantAction' => ['privates', '.service_locator.xqhtgkX', 'get_ServiceLocator_XqhtgkXService', true],
            'App\\Controller\\AdminController::employesAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController::employetouserAction' => ['privates', '.service_locator.xqhtgkX', 'get_ServiceLocator_XqhtgkXService', true],
            'App\\Controller\\AdminController::groslotAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController::groswinAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController::newgameAction' => ['privates', '.service_locator.nqkifCm', 'get_ServiceLocator_NqkifCmService', true],
            'App\\Controller\\AdminController::participanttouserAction' => ['privates', '.service_locator.xqhtgkX', 'get_ServiceLocator_XqhtgkXService', true],
            'App\\Controller\\AdminController::refait' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController::usersAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator..Onmb1X', 'get_ServiceLocator__Onmb1XService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.KvjBBvm', 'get_ServiceLocator_KvjBBvmService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:deleteparticipantAction' => ['privates', '.service_locator.xqhtgkX', 'get_ServiceLocator_XqhtgkXService', true],
            'App\\Controller\\AdminController:employesAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController:employetouserAction' => ['privates', '.service_locator.xqhtgkX', 'get_ServiceLocator_XqhtgkXService', true],
            'App\\Controller\\AdminController:groslotAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController:groswinAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController:newgameAction' => ['privates', '.service_locator.nqkifCm', 'get_ServiceLocator_NqkifCmService', true],
            'App\\Controller\\AdminController:participanttouserAction' => ['privates', '.service_locator.xqhtgkX', 'get_ServiceLocator_XqhtgkXService', true],
            'App\\Controller\\AdminController:refait' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\AdminController:usersAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator..Onmb1X', 'get_ServiceLocator__Onmb1XService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.KvjBBvm', 'get_ServiceLocator_KvjBBvmService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::deleteparticipantAction' => '?',
            'App\\Controller\\AdminController::employesAction' => '?',
            'App\\Controller\\AdminController::employetouserAction' => '?',
            'App\\Controller\\AdminController::groslotAction' => '?',
            'App\\Controller\\AdminController::groswinAction' => '?',
            'App\\Controller\\AdminController::newgameAction' => '?',
            'App\\Controller\\AdminController::participanttouserAction' => '?',
            'App\\Controller\\AdminController::refait' => '?',
            'App\\Controller\\AdminController::usersAction' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:deleteparticipantAction' => '?',
            'App\\Controller\\AdminController:employesAction' => '?',
            'App\\Controller\\AdminController:employetouserAction' => '?',
            'App\\Controller\\AdminController:groslotAction' => '?',
            'App\\Controller\\AdminController:groswinAction' => '?',
            'App\\Controller\\AdminController:newgameAction' => '?',
            'App\\Controller\\AdminController:participanttouserAction' => '?',
            'App\\Controller\\AdminController:refait' => '?',
            'App\\Controller\\AdminController:usersAction' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
