<?php

namespace ContainerYgY6cL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCustomAutAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AppCustomAutAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppCustomAutAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppCustomAutAuthenticator'] = new \App\Security\AppCustomAutAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
