<?php

namespace ContainerYgY6cL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDistributedTicketsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DistributedTicketsRepository' shared autowired service.
     *
     * @return \App\Repository\DistributedTicketsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DistributedTicketsRepository'] = new \App\Repository\DistributedTicketsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
