<?php

namespace ContainerYgY6cL5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TicketsRepository' shared autowired service.
     *
     * @return \App\Repository\TicketsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TicketsRepository'] = new \App\Repository\TicketsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
