version: '3'
services:
  app:
    image: blaghmi97/symfonyapp:main
    container_name: symfony_app_main
    volumes:
      - ${WORKSPACE_DIR}:/var/www
    depends_on:
      - database
    networks:
      - symfony

  database:
    image: mysql:latest
    container_name: symfony_mysql_main
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_project
      MYSQL_PASSWORD: password
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  webserver:
    image: nginx:alpine
    container_name: symfony_webserver_main
    volumes:
      - ${WORKSPACE_DIR}:/var/www
      - ${WORKSPACE_DIR}/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ${WORKSPACE_DIR}/nginx/dsp-archiwebf21-yb.fr.crt:/etc/nginx/ssl/dsp-archiwebf21-yb.fr.crt
      - ${WORKSPACE_DIR}/nginx/dsp-archiwebf21-yb.fr.deprotected.key:/etc/nginx/ssl/dsp-archiwebf21-yb.fr.deprotected.key

    depends_on:
      - app
    networks:
      - symfony
    ports:
      - "80:80"
      - "443:443"
networks:
  symfony:
  mysql-phpmyadmin:


volumes:
  db_data:
