<?php

namespace ContainerVTbyWBX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5DPrr7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5DPrr_7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5DPrr_7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dt' => ['privates', 'App\\Repository\\DistributedTicketsRepository', 'getDistributedTicketsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'games' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'tickets' => ['privates', 'App\\Repository\\TicketsRepository', 'getTicketsRepositoryService', true],
        ], [
            'dt' => 'App\\Repository\\DistributedTicketsRepository',
            'em' => '?',
            'games' => 'App\\Repository\\GameRepository',
            'tickets' => 'App\\Repository\\TicketsRepository',
        ]);
    }
}
