<?php

namespace ContainerVTbyWBX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EUu1dxmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eUu1dxm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eUu1dxm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::deleteparticipantAction' => ['privates', '.service_locator.fJ7NaTH', 'get_ServiceLocator_FJ7NaTHService', true],
            'App\\Controller\\AdminController::employesAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::employetouserAction' => ['privates', '.service_locator.fJ7NaTH', 'get_ServiceLocator_FJ7NaTHService', true],
            'App\\Controller\\AdminController::groslotAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::groswinAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::newgameAction' => ['privates', '.service_locator.5DPrr_7', 'get_ServiceLocator_5DPrr7Service', true],
            'App\\Controller\\AdminController::participanttouserAction' => ['privates', '.service_locator.fJ7NaTH', 'get_ServiceLocator_FJ7NaTHService', true],
            'App\\Controller\\AdminController::refait' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController::usersAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.4grtgyb', 'get_ServiceLocator_4grtgybService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator..PWwUYY', 'get_ServiceLocator__PWwUYYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AdminController:deleteparticipantAction' => ['privates', '.service_locator.fJ7NaTH', 'get_ServiceLocator_FJ7NaTHService', true],
            'App\\Controller\\AdminController:employesAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:employetouserAction' => ['privates', '.service_locator.fJ7NaTH', 'get_ServiceLocator_FJ7NaTHService', true],
            'App\\Controller\\AdminController:groslotAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:groswinAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:newgameAction' => ['privates', '.service_locator.5DPrr_7', 'get_ServiceLocator_5DPrr7Service', true],
            'App\\Controller\\AdminController:participanttouserAction' => ['privates', '.service_locator.fJ7NaTH', 'get_ServiceLocator_FJ7NaTHService', true],
            'App\\Controller\\AdminController:refait' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\AdminController:usersAction' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.4grtgyb', 'get_ServiceLocator_4grtgybService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator..PWwUYY', 'get_ServiceLocator__PWwUYYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AdminController::deleteparticipantAction' => '?',
            'App\\Controller\\AdminController::employesAction' => '?',
            'App\\Controller\\AdminController::employetouserAction' => '?',
            'App\\Controller\\AdminController::groslotAction' => '?',
            'App\\Controller\\AdminController::groswinAction' => '?',
            'App\\Controller\\AdminController::newgameAction' => '?',
            'App\\Controller\\AdminController::participanttouserAction' => '?',
            'App\\Controller\\AdminController::refait' => '?',
            'App\\Controller\\AdminController::usersAction' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:deleteparticipantAction' => '?',
            'App\\Controller\\AdminController:employesAction' => '?',
            'App\\Controller\\AdminController:employetouserAction' => '?',
            'App\\Controller\\AdminController:groslotAction' => '?',
            'App\\Controller\\AdminController:groswinAction' => '?',
            'App\\Controller\\AdminController:newgameAction' => '?',
            'App\\Controller\\AdminController:participanttouserAction' => '?',
            'App\\Controller\\AdminController:refait' => '?',
            'App\\Controller\\AdminController:usersAction' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
