<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT2JNBGd\App_KernelPreprodDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT2JNBGd/App_KernelPreprodDebugContainer.php') {
    touch(__DIR__.'/ContainerT2JNBGd.legacy');

    return;
}

if (!\class_exists(App_KernelPreprodDebugContainer::class, false)) {
    \class_alias(\ContainerT2JNBGd\App_KernelPreprodDebugContainer::class, App_KernelPreprodDebugContainer::class, false);
}

return new \ContainerT2JNBGd\App_KernelPreprodDebugContainer([
    'container.build_hash' => 'T2JNBGd',
    'container.build_id' => 'd1ebeed7',
    'container.build_time' => 1711285034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT2JNBGd');
